# Generated by Django 3.1.7 on 2021-06-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='Link',
            new_name='link',
        ),
    ]
